sudo: required
language: python
cache: pip
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
    allow_failures:
    - python: 2.7
    - python: 3.7
      dist: xenial
services:
    - docker
    - mongodb
    - rabbitmq
    - redis-server
    - mysql
    #- elasticsearch
    - postgresql
addons:
  postgresql: "9.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y beanstalkd
    - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
    - sudo service beanstalkd start
    - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.0.deb && sudo service elasticsearch restart
    - sudo docker pull scrapinghub/splash
    - sudo docker run -d --net=host scrapinghub/splash
before_script:
    - psql -c "CREATE DATABASE pyspider_test_taskdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - psql -c "CREATE DATABASE pyspider_test_projectdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - psql -c "CREATE DATABASE pyspider_test_resultdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - sleep 10
install:
    - pip install https://github.com/marcus67/easywebdav/archive/master.zip
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install libc6; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then sudo apt-get install libgnutls28-dev; fi
    - pip install -e .[all,test]
    - pip install coveralls
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
